name: Trading Signal Scanner

on:
  schedule:
    - cron: '*/15 * * * *' # Berjalan otomatis setiap 15 menit
  workflow_dispatch: # Memungkinkan Anda menjalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests

      - name: Run scanner
        run: python scanner.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Auto Update Signal" || exit 0
          git push
